import StyleType from "../../types/Style";

const styles: Record<string, StyleType> = {
    'A': {
        letter: 'A',
        diamond: false,
        bgColor: 'mtaBlue',
        accentBgColor: 'blue.100',
        darkAccentBgColor: 'blue.200',
    },
    'C': {
        letter: 'C',
        diamond: false,
        bgColor: 'mtaBlue',
        accentBgColor: 'blue.100',
        darkAccentBgColor: 'blue.200',
    },
    'E': {
        letter: 'E',
        diamond: false,
        bgColor: 'mtaBlue',
        accentBgColor: 'blue.100',
        darkAccentBgColor: 'blue.200',
    },
    'B': {
        letter: 'B',
        diamond: false,
        bgColor: 'mtaOrange',
        accentBgColor: 'orange.100',
        darkAccentBgColor: 'orange.200',
    },
    'D': {
        letter: 'D',
        diamond: false,
        bgColor: 'mtaOrange',
        accentBgColor: 'orange.100',
        darkAccentBgColor: 'orange.200',
    },
    'F': {
        letter: 'F',
        diamond: false,
        bgColor: 'mtaOrange',
        accentBgColor: 'orange.100',
        darkAccentBgColor: 'orange.200',
    },
    'FX': {
      letter: 'F',
      diamond: true,
      bgColor: 'mtaOrange',
        accentBgColor: 'orange.100',
        darkAccentBgColor: 'orange.200',
    },
    'M': {
        letter: 'M',
        diamond: false,
        bgColor: 'mtaOrange',
        accentBgColor: 'orange.100',
        darkAccentBgColor: 'orange.200',
    },
    'G': {
        letter: 'G',
        diamond: false,
        bgColor: 'mtaLime',
        accentBgColor: 'gAccent',
        darkAccentBgColor: 'gDarkAccent',
    },
    'L': {
        letter: 'L',
        diamond: false,
        bgColor: 'mtaGray',
        accentBgColor: 'blueGray.200',
        darkAccentBgColor: 'blueGray.300',
    },
    'N': {
        letter: 'N',
        diamond: false,
        bgColor: 'mtaYellow',
        accentBgColor: 'yellowAccent',
        darkAccentBgColor: 'yellow.200',
    },
    'Q': {
        letter: 'Q',
        diamond: false,
        bgColor: 'mtaYellow',
        accentBgColor: 'yellowAccent',
        darkAccentBgColor: 'yellow.200',
    },
    'R': {
      letter: 'R',
      diamond: false,
      bgColor: 'mtaYellow',
        accentBgColor: 'yellowAccent',
        darkAccentBgColor: 'yellow.200',
    },
    'W': {
      letter: 'W',
      diamond: false,
      bgColor: 'mtaYellow',
        accentBgColor: 'yellowAccent',
        darkAccentBgColor: 'yellow.200',
    },
    'J': {
      letter: 'J',
      diamond: false,
      bgColor: 'mtaBrown',
      accentBgColor: 'brownAccent',
      darkAccentBgColor: 'brownDarkAccent',
    },
    'Z': {
      letter: 'Z',
      diamond: false,
      bgColor: 'mtaBrown',
      accentBgColor: 'brownAccent',
      darkAccentBgColor: 'brownDarkAccent',
    },
    '1': {
      letter: '1',
      diamond: false,
      bgColor: 'mtaRed',
      accentBgColor: 'red.100',
      darkAccentBgColor: 'red.200',
    },
    '2': {
      letter: '2',
      diamond: false,
      bgColor: 'mtaRed',
      accentBgColor: 'red.100',
      darkAccentBgColor: 'red.200',
    },
    '3': {
      letter: '3',
      diamond: false,
      bgColor: 'mtaRed',
      accentBgColor: 'red.100',
      darkAccentBgColor: 'red.200',
    },
    '4': {
      letter: '4',
      diamond: false,
      bgColor: 'mtaGreen',
      accentBgColor: 'greenAccent',
      darkAccentBgColor: 'greenDarkAccent',
    },
    '5': {
      letter: '5',
      diamond: false,
      bgColor: 'mtaGreen',
      accentBgColor: 'greenAccent',
      darkAccentBgColor: 'greenDarkAccent',
    },
    '6': {
      letter: '6',
      diamond: false,
      bgColor: 'mtaGreen',
      accentBgColor: 'greenAccent',
      darkAccentBgColor: 'greenDarkAccent',
    },
    '6X': {
      letter: '6',
      diamond: true,
      bgColor: 'mtaGreen',
      accentBgColor: 'greenAccent',
      darkAccentBgColor: 'greenDarkAccent',
    },
    '7': {
      letter: '7',
      diamond: false,
      bgColor: 'mtaPurple',
      accentBgColor: 'purple.100',
      darkAccentBgColor: 'purple.300',
    },
    '7X': {
      letter: '7',
      diamond: true,
      bgColor: 'mtaPurple',
      accentBgColor: 'purple.100',
      darkAccentBgColor: 'purple.300',
  },
    'FS': {
        letter: 'S',
        diamond: false,
        bgColor: 'mtaDarkGray',
        accentBgColor: 'gray.200',
        darkAccentBgColor: 'gray.300',
    },
    'GS': {
        letter: 'S',
        diamond: false,
        bgColor: 'mtaDarkGray',
        accentBgColor: 'gray.200',
        darkAccentBgColor: 'gray.300',
    },
    'H': {
        letter: 'S',
        diamond: false,
        bgColor: 'mtaDarkGray',
        accentBgColor: 'gray.200',
        darkAccentBgColor: 'gray.300',
    },
    'SI': {
      letter: 'S',
      diamond: false,
      bgColor: 'mtaBlue',
      accentBgColor: 'blue.100',
      darkAccentBgColor: 'blue.200',
  },
  'SIR': {
    letter: 'S',
    diamond: false,
    bgColor: 'mtaBlue',
    accentBgColor: 'blue.100',
    darkAccentBgColor: 'blue.200',
  },
}
export default styles;